spin_manifest_version = 2

[application]
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""
name = "bullsncows"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "bullsncows"

[component.bullsncows]
source = "target/bullsncows.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
[component.bullsncows.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
