spin_manifest_version = 2

[application]
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""
name = "bullsncows"
version = "0.1.0"

[[trigger.http]]
route = "/api"
component = "bullsncows"

[component.bullsncows]
source = "target/bullsncows.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
[component.bullsncows.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]

[[trigger.http]]
route = "/..."
component = "fs"

[component.fs]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "assets", destination = "/" }]
